Add rules for unnecessary uses of with() and values() functions
nunomaduro/larastan pull request #1226
Opened 2022-05-03 20:31 UTC by PrinsFrank

- [x] Added or updated tests
- [x] Documented user facing changes
- [x] Updated CHANGELOG.md

**Changes**
- feat: add Rule checking for useless 'with()' function calls
- feat: add Rule checking for useless 'value()' function calls

**Breaking changes**
None

2022-05-03 20:50 UTC, szepeviktor commented on CHANGELOG.md
> +* feat: add Rule checking for useless 'value()' function calls by @PrinsFrank in https://github.com/nunomaduro/larastan/pull/1226
You could merge these lines.

2022-05-03 20:53 UTC, PrinsFrank commented on CHANGELOG.md
> +* feat: add Rule checking for useless 'value()' function calls by @PrinsFrank in https://github.com/nunomaduro/larastan/pull/1226
Thanks for looking at this so quickly!

2022-05-03 20:58 UTC, szepeviktor commented
[non-official] I think you won't get away with these rules enabled by default.

2022-05-03 21:07 UTC, PrinsFrank commented
> [non-official] I think you won't get away with these rules enabled by default.

@szepeviktor What would you suggest? Adding these as rules that can be enabled using configuration?
I wouldn't say these are opinionated rules as they detect code that doesn't do anything.

2022-05-03 21:18 UTC, szepeviktor commented
> I wouldn't say these are opinionated rules as they detect code that doesn't do anything.

I'm just a janitor here!

2022-05-23 16:38 UTC, canvural requested changes

2022-05-23 16:38 UTC, canvural commented on src/Rules/UselessConstructs/NoUselessValueFunctionCallsRule.php
> +        if ($node->name->toString() !== 'value') {
Please use `strtolower` here for left handside.

2022-05-23 16:38 UTC, canvural commented on src/Rules/UselessConstructs/NoUselessValueFunctionCallsRule.php
> +        if ($args[0]->value instanceof Node\Expr\Closure) {
We need to check if `count($args)` is greater than 1 before here.

Also using the `instanceof` check here with the `Closure` is wrong here. This wouldn't work for example union or intersection types. Instead we should ask the type system about this. You can use `$scope->getType($args[0]->value)` to get the type for the variable. And use `isSuperTypeOf` to compare the types. You can read more about the type system [here.](https://phpstan.org/developing-extensions/type-system)

2022-05-23 16:38 UTC, canvural commented on src/Rules/UselessConstructs/NoUselessValueFunctionCallsRule.php
> +        return ["Calling the helper function 'value()' without a closure as the first argument simply returns the first argument without doing anything"];
Please use `RuleErrorBuilder` to construct the error. You can check other rules to see how it is done.

2022-05-23 16:38 UTC, canvural commented on src/Rules/UselessConstructs/NoUselessWithFunctionCallsRule.php
> +        if ($args[1]->value instanceof Node\Expr\Closure || ($args[1]->value instanceof Node\Scalar\String_ && function_exists($args[1]->value->value))) {
`$args` is not guaranteed to have index `1` here. Please do a check before.

Also, same as the previous comment; please use the type system to do the checks here.

2022-05-23 16:38 UTC, canvural commented on src/Rules/UselessConstructs/NoUselessWithFunctionCallsRule.php
> +        return ["Calling the helper function 'with()' without a closure as the second argument simply returns the value without doing anything"];
ditto. `RuleErrorBuilder` to construct the message.

2022-05-23 16:38 UTC, canvural commented on tests/Rules/UselessConstructs/NoUselessValueFunctionCallsRuleTest.php
> +class NoUselessValueFunctionCallsRuleTest extends RulesTest
Please extend `RuleTestCase` here instead of `RulesTest` And change the rest of the class according to it.

2022-05-23 16:38 UTC, canvural commented on tests/Rules/UselessConstructs/NoUselessWithFunctionCallsRuleTest.php
> +class NoUselessWithFunctionCallsRuleTest extends RulesTest
ditto. extend `RuleTestCase`

2022-06-03 16:18 UTC, canvural commented
Hi, are you gonna finish this?

2022-06-03 16:47 UTC, PrinsFrank commented
Sorry, was preoccupied with a job switch. Will finish this now!

2022-06-03 17:43 UTC, szepeviktor approved these changes

2022-07-19 21:55 UTC, PrinsFrank commented
@szepeviktor @canvural @nunomaduro I'm cleaning up my forks, can I assume this is not going to get merged and close this PR?

2022-07-19 21:58 UTC, szepeviktor commented
@PrinsFrank Please do not delete your fork.

We _will_ take a look at it and merge it.

2022-07-19 22:13 UTC, PrinsFrank commented
@szepeviktor Ok, np!

2022-08-23 17:08 UTC, merged

2022-08-23 17:09 UTC, canvural commented
Thank you! I pushed some commits to simplify some bits.