Allow Builder-s in Builder::union* $query parameter
nunomaduro/larastan pull request #1231
Opened 2022-05-13 16:21 UTC by fagai

- [ ] Added or updated tests
- [ ] Documented user facing changes
- [ ] Updated CHANGELOG.md

related: https://github.com/laravel/framework/pull/42374

The Builder::union method is supports `Illuminate\Database\Eloquent\Builder`, but an error occurs because there is no description.

**Steps to reproduce**

```php
$first = User::where('id',8);

$users = User::where('id',2)->union($first)->get();
```

**Error Report**

```
Parameter #1 $query of method Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>::union() expects Closure|Illuminate\Database\Query\Builder, Illuminate\Database\Eloquent\Builder given.
```

**Description**

**`Illuminate\Database\Eloquent\Builder` is not a subtype of `Illuminate\Database\Query\Builder`.**

Illuminate\Database\Eloquent\Builder
```php
use Illuminate\Contracts\Database\Eloquent\Builder as BuilderContract;
class Builder implements BuilderContract
{
```

Illuminate\Database\Query\Builder
```php
use Illuminate\Contracts\Database\Query\Builder as BuilderContract;
class Builder implements BuilderContract
{
```

**Changes**

Added type.

**Breaking changes**

no

2022-05-13 16:33 UTC, szepeviktor commented
Hello @fagai! 👋
Thank you for your contributions.
`Builder` is a generic class, please see
https://github.com/nunomaduro/larastan/blob/1162e3b3ca2cee6ab77b67bfdf20d598ebf50f20/stubs/QueryBuilder.stub#L139

2022-05-13 16:43 UTC, fagai commented
@szepeviktor 
Thank you!
changed parameter.

2022-05-13 16:48 UTC, szepeviktor commented
どういたしまして！

2022-05-13 16:54 UTC, szepeviktor commented
Just add `* @template TModelClass of \Illuminate\Database\Eloquent\Model` to both docblocks and we are done 🚀

2022-05-13 17:00 UTC, fagai commented
@szepeviktor 
OK, Thank you!

2022-05-13 17:34 UTC, szepeviktor approved these changes

2022-05-23 16:42 UTC, canvural requested changes
Hi,

Thank you for this! Just 2 small nitpicks.

2022-05-23 16:42 UTC, canvural commented on stubs/QueryBuilder.stub
> +	 * @template TModelClass of \Illuminate\Database\Eloquent\Model
Wrong indentation here.

2022-05-23 16:42 UTC, canvural commented on stubs/QueryBuilder.stub
> +	 * @template TModelClass of \Illuminate\Database\Eloquent\Model
Wrong indentation here.

2022-05-23 16:43 UTC, merged

2022-05-23 16:43 UTC, canvural commented
Ignore the previous comments. Github's diff viewer fooled me. 

Thank you!

2022-05-23 16:50 UTC, szepeviktor commented
> Github's diff viewer fooled me.

@canvural Actually those were TAB characters.
Please see https://github.com/nunomaduro/larastan/commit/be2c6b316686513964b925e8024314edc6b4832a

2022-05-23 16:56 UTC, canvural commented
@szepeviktor Ah, thank you!