feat: refined return type of safe method.
nunomaduro/larastan pull request #1417
Opened 2022-10-19 18:53 UTC by jdjfisher

- [x] Added or updated tests
- [x] Documented user facing changes
- [x] Updated CHANGELOG.md

**Changes**

Refines the return types of the `\Illuminate\Foundation\Http\FormRequest::safe` and `\Illuminate\Validation\Validator::safe` methods.

2022-10-19 18:57 UTC, szepeviktor commented
Do not worry about monicahq! This is our tech debt.

2022-10-19 19:07 UTC, jdjfisher commented
> Your IDE may not read EditorConfig

Whoops, those missing eols should be sorted now 👍

2022-10-19 19:14 UTC, szepeviktor approved these changes

2022-10-19 19:14 UTC, szepeviktor commented
Very nice work 💎

2022-10-19 20:55 UTC, canvural requested changes
One tiny thing. Other than that it looks good 👍🏽

2022-10-19 20:55 UTC, canvural commented on tests/Type/data/form-request.php
> +namespace ValidatorSafe;
Please use different namespace for this file. For example `FormRequest`

2022-10-20 07:11 UTC, merged

2022-10-20 07:11 UTC, canvural commented
Thank you!