fix duplicate SQL parsing and add docs
nunomaduro/larastan pull request #1569
Opened 2023-03-04 04:21 UTC by CalebDW

- [ ] Added or updated tests
- [ ] Documented user facing changes

**Changes**
The SQL Parser calls `Parser::parse` in the constructor so I removed the duplicate call.

I also added some docs about Laravel 9 attributes and PostgreSQL dumps.

**Breaking changes**
N/A

2023-03-04 21:08 UTC, canvural commented
Hi,

Thank you for this!

But maybe having a separate new features documentation in `docs/` folder would be better. To not clutter the README. Then we can reference it from README. What do you think?

2023-03-04 21:44 UTC, CalebDW commented
@canvural, something I noted in the docs is that the sql parser can take a very long time parsing Postgres dumps (over 7 minutes for a <1MB file... only to return no tables). This is going to become a problem because the dumps are parsed automatically. I could point `squashedMigrationsPath` to a non-existent/empty directory but it would be more useful to just have an option disabling the parsing.

2023-03-04 21:54 UTC, szepeviktor commented
Great work has been done on master. Please consider rebasing.

2023-03-04 21:57 UTC, szepeviktor commented
Your commits are made with a non-GitHub email address.
If you want you can use your email address registered here on GitHub.

2023-03-05 03:06 UTC, CalebDW commented
> Your commits are made with a non-GitHub email address. If you want you can use your email address registered here on GitHub.

Ah good catch, how do I update the commits?

2023-03-08 21:28 UTC, canvural requested changes

2023-03-08 21:31 UTC, CalebDW commented on docs/features.md
> +
Ah good catch.

2023-03-08 21:31 UTC, CalebDW commented on README.md
> +A list of features specific to Laravel can be found [here](docs/features.md).
Fixed.

2023-03-08 21:46 UTC, merged

2023-03-08 21:46 UTC, canvural commented
Thank you!