feat: Add new BenchmarkExtension
nunomaduro/larastan pull request #1796
Opened 2023-12-06 21:01 UTC by jesperbeisner

- [x] Added or updated tests
- [ ] Documented user facing changes

**Changes**

Added new BenchmarkExtension for right return types.

**Breaking changes**

None

2023-12-07 05:31 UTC, jesperbeisner commented
I'm really not sure what's up with these failing tests. To my understanding this has nothing to do with my new extension?! :eyes:

2023-12-07 07:10 UTC, szepeviktor commented
Those three repositories use `nunomaduro/larastan`, that causes an error.

2023-12-10 23:02 UTC, canvural requested changes
Hi,

This extension can be replaced by only a PHPDoc. Please put the following PHPDoc into a stub file and delete the extension. But don't modify the tests, they should still pass:
```php
/**
 * Measure a callable or array of callables over the given number of iterations.
 *
 * @template TKey
 * @param  \Closure|array<TKey, \Closure>  $benchmarkables
 * @param  int  $iterations
 * @return ($benchmarkables is \Closure ? float : array<TKey, float>)
 */
```

2023-12-10 23:03 UTC, canvural commented
> I'm really not sure what's up with these failing tests. To my understanding this has nothing to do with my new extension?! 👀

Yeah errors were not related to this PR. And now they've been fixed. So if you rebase your branch, you'll see them passing here.

2023-12-15 08:29 UTC, jesperbeisner commented
You learn something new every day, very cool! :muscle:

2023-12-15 08:35 UTC, szepeviktor commented on stubs/common/Support/Benchmark.stub
> +namespace Illuminate\Support;
```suggestion
use Closure;
```

2023-12-15 08:43 UTC, jesperbeisner commented on stubs/common/Support/Benchmark.stub
> +namespace Illuminate\Support;
Ooops 😅

2024-01-02 21:54 UTC, CanVuralStudocu approved these changes

2024-01-02 21:55 UTC, canvural approved these changes

2024-01-02 21:58 UTC, merged

2024-01-02 21:58 UTC, canvural commented
Thank you!