Add stubs for Collection->pop and Collection->shift
nunomaduro/larastan pull request #1827
Opened 2024-01-31 05:26 UTC by simon-tma

If a `$count` of 1 is provided, these methods return a value or null.

If any other `$count` is provided, these methods return a collection.

- [x] Added or updated tests
- [ ] Documented user facing changes

**Changes**

Adds stubs for `Collection->pop()` and `Collection->shift()` that adds a conditional return type on the `$count`

**Breaking changes**

2024-02-01 10:56 UTC, canvural requested changes
Looks good 👍🏽 

Just left one thing about tests. Please also apply it to other removed tests.

2024-02-01 10:56 UTC, canvural commented on tests/Type/data/collection-generic-static-methods.php
> -assertType('Illuminate\Support\Collection<int, int>|int|null', $items->pop(3));
Can you fix the assertions instead of deleting the test cases? Here we are actually testing something else.

2024-02-01 21:48 UTC, simon-tma commented
Have restored and corrected those tests. Let me know if you'd also like me to add checks for the singular return vs the collection return for all of them too.

2024-02-02 09:54 UTC, canvural commented
> Have restored and corrected those tests. Let me know if you'd also like me to add checks for the singular return vs the collection return for all of them too.

Thank you! This looks good. Build failure doesn't seem to be related to this one. I'll investigate that.

2024-02-02 10:29 UTC, szepeviktor commented
Latest Laravel 11 may have introduced changes
https://github.com/larastan/larastan/actions/runs/7749285580/job/21133539947

2024-02-11 18:21 UTC, canvural commented
Hi,

Could you rebase your changes? CI should run then.

2024-02-12 01:17 UTC, szepeviktor commented on tests/Type/data/collection-generic-static-methods.php
> +assertType('App\TransactionCollection<int, App\Transaction>:, $customEloquentCollection->shift(2));
```suggestion
assertType('App\TransactionCollection<int, App\Transaction>', $customEloquentCollection->shift(2));
```

2024-02-12 15:50 UTC, merged

2024-02-12 15:50 UTC, canvural commented
Thank you.