Fix not respecting return type of overridden Request::user() method.
nunomaduro/larastan pull request #1861
Opened 2024-02-19 14:20 UTC by mad-briller

- [x] Added or updated tests

closes https://github.com/larastan/larastan/issues/1718

**Changes**

Change RequestUserExtension to use the specific type of an overridden `Request::user()` method

2024-02-19 18:15 UTC, calebdw commented on tests/Type/GeneralTypeTest.php
> +        yield from self::gatherAssertTypes(__DIR__.'/data/bug-1718.php');
I would put this with the other bugs

2024-02-19 18:17 UTC, calebdw commented
You beat me to this!

2024-02-20 21:46 UTC, canvural requested changes
Looks good. Thanks.

Just left a one comment. Also the branch has merge conflicts now. That's why it is a good idea to put any test case in `GeneralTypeTest` to at the end of the file. The order of the tests do not matter at all 😊

2024-02-20 21:46 UTC, canvural commented on src/ReturnTypes/RequestUserExtension.php
> +            return ParametersAcceptorSelector::selectSingle($methodReflection->getVariants())->getReturnType();
Can't we return `null` here?

2024-02-20 21:54 UTC, calebdw commented
> Also the branch has merge conflicts now. That's why it is a good idea to put any test case in GeneralTypeTest to at the end of the file. The order of the tests do not matter at all 😊

I get that order does not matter (other than for aesthetics), but you would still have merge conflicts if two separate PRs placed files in the same spot at the end of the file.

2024-05-20 08:45 UTC, mad-briller commented
i'll get to this proper when i have some time after work

2024-07-09 06:13 UTC, HDVinnie commented
Whats the status on this @mad-briller @calebdw @canvural

2024-07-09 06:32 UTC, szepeviktor commented
This PR need to be fixed.

2024-09-06 11:19 UTC, mad-briller commented
not sure what's going on with CI, appears to be some stuff broken outside the scope of this pr
but this pr should be ready now, sorry for the delay it slipped my mind

2024-09-06 12:29 UTC, calebdw commented
Awesome thanks! Laravel 11 tests are broken until #1990 is merged and the other tests are failing due to PHPstan 1.12 which will be fixed with #2028

2024-09-27 16:28 UTC, merged

2024-09-27 16:28 UTC, canvural commented
Thank you!