Add chunk* and each* methods to Eloquent Builder stub
nunomaduro/larastan pull request #1969
Opened 2024-06-09 07:17 UTC by leo108

- [ ] Added or updated tests
- [ ] Documented user facing changes

2024-06-16 23:29 UTC, leo108 commented
@canvural any chance to check this PR? let me know if you have any idea, thanks!

2024-06-21 05:25 UTC, calebdw commented on stubs/common/EloquentBuilder.stub
> +     * @param  callable(TModelClass): mixed $callback
The callable takes two args (the other method and files need to fixed as well).

```suggestion
     * @param  callable(TModelClass, int): mixed $callback
```

2024-06-21 05:31 UTC, calebdw reviewed
Missing some args

2024-06-21 05:55 UTC, leo108 commented
@calebdw Thanks for the review, the missing arg has been added, I also add the missing arg to eachById method, please check again.

2024-07-06 06:50 UTC, leo108 commented
@canvural Can you check this PR when you have chance?

2024-07-06 18:02 UTC, canvural requested changes

2024-07-06 18:02 UTC, canvural commented on tests/Type/GeneralTypeTest.php
> +        }
We are adding the stubs to `10.0.0` anyway. So it'll be available for 10.x. No need to check for 10.27 specifically.

If there is a big change before and after 10.27, then you need to create a folder `10.27.0` in `stubs` directory and put the stubs there.

2024-07-06 18:02 UTC, canvural commented on tests/Type/data/eloquent-builder-l10-27.php
> +namespace ModelRelations;
```suggestion
namespace EloquentBuilderL1027;
```

or something like that

2024-07-06 18:02 UTC, canvural commented on stubs/common/EloquentBuilder.stub
> +     * @template TReturn of mixed
```suggestion
     * @template TReturn
```

you don't need that last part.

2024-11-18 22:30 UTC, rudiedirkx commented
Seems like all of this is in `2.x` already?

2025-02-20 22:02 UTC, closed without merging