Query chunk() custom collection class
nunomaduro/larastan pull request #2121
Opened 2024-11-18 22:37 UTC by rudiedirkx

- [ ] Added or updated tests
- <s>Documented user facing changes</s>

Fixes #2079 

**Changes**

Phpdoc didn't support custom model collection, only `EloquentCollection`:

```
@param  callable(\Illuminate\Database\Eloquent\Collection<int, TModelClass>, int): mixed  $callback
```

This new extension (first of `MethodParameterClosureTypeExtension` 😮) uses `CollectionHelper` to find the specific collection.

**Breaking changes**

None.

2024-11-18 22:46 UTC, rudiedirkx commented
`chunk()` unit tests fail with

```diff
--- Expected
+++ Actual
@@ @@
-'Illuminate\Database\Eloquent\Collection<int, App\User>'
+'mixed'
```

maybe because the detailed phpdoc is gone, but the extension isn't used? Why isn't the extension used?

2024-11-18 22:53 UTC, calebdw requested changes
This should target 3.x as that's the newest release. Laravel 10 has reached EOL and Larastan 2.x should be sunsetting

2024-11-18 22:53 UTC, calebdw commented on src/Methods/CollectionChunkClosureTypeExtension.php
> +        if (!in_array($methodReflection->getName(), ['chunk', 'chunkById', 'chunkByIdDesc'])) {
prefer strict mode:

```suggestion
        if (!in_array($methodReflection->getName(), ['chunk', 'chunkById', 'chunkByIdDesc'], strict: true)) {
```

2024-11-18 22:53 UTC, calebdw commented on src/Methods/CollectionChunkClosureTypeExtension.php
> +        return (new ObjectType(EloquentBuilder::class))->isSuperTypeOf(new ObjectType($methodReflection->getDeclaringClass()->getName()))->yes();
Use this instead:

```suggestion
        return $methodReflection->getDeclaringClass()->is(EloquentBuilder::class);
```

2024-11-18 22:53 UTC, calebdw commented on stubs/11.0.0/EloquentBuilder.stub
stubs should not be changed

2024-11-18 23:10 UTC, rudiedirkx commented
> stubs should not be changed

It won't work then. Apparently an extension can't undo or overwrite the phpdoc `callback` details.

And some more failing tests that I don't understand. I'm not willing to put more hours in for probably very simple issues that I don't understand. I'll take a look after the professionals do their thing.

2024-11-18 23:14 UTC, calebdw commented
> Apparently an extension can't undo or overwrite the phpdoc callback details.

You're mistaken, extensions override phpdocs all the time

2024-11-18 23:42 UTC, rudiedirkx commented
I couldn't get it to work. Only like this. I tried all combinations of Laravel's phpdoc + Larastan's phpdoc.

2024-12-04 13:21 UTC, rudiedirkx commented
@calebdw It really doesn't work without messing up the phpdoc. (Phpstan 1.x still.) The extension works perfectly, and it returns the perfect `ClosureType`, but Phpstan doesn't use it. Could you look at it and tell me what I'm doing wrong/how Phpstan works?

2025-02-20 22:45 UTC, canvural commented
Hi,

Thank you for the PR. But currently there are some issues with the `*ParameterClosureTypeExtension` extensions. I already had changes prepared to use the new extensions, but the bugs are keeping me from releasing them. 

I'll close this for now, and when the bugs related to extensions are fixed I'll implement them here.

2025-02-20 22:45 UTC, closed without merging