Fix Dynamic call to static method Illuminate\Foundation\Application::configurationIsCached()
nunomaduro/larastan pull request #917
Opened 2021-08-14 16:27 UTC by LastDragon-ru

- [ ] Added or updated tests
- [ ] Documented user facing changes
- [ ] Updated CHANGELOG.md

**Changes**

larastan + phpstan-strict generates false positives (related to #483):

```
Dynamic call to static method  Illuminate\Foundation\Application::configurationIsCached().
```

this PR seems to fix it.

**Breaking changes**

Not sure.

_PS: If needed I can provide link to reproduce._

2021-08-14 16:41 UTC, szepeviktor commented
@LastDragon-ru Thank you for the PR!

Big Tragedy! Unit tests fail.

2021-08-14 16:51 UTC, LastDragon-ru commented
> Big Tragedy! Unit tests fail.

Not sure that it is related to the PR 🤔

```
-- --------------------------------------------------------------------------- 
     Error                                                                      
 -- --------------------------------------------------------------------------- 
     Child process error (exit code 255): PHP Fatal error:  Declaration of      
     Illuminate\Http\Response::setContent($content) must be compatible with     
     Symfony\Component\HttpFoundation\Response::setContent(?string $content):   
     static in                                                                  
     /home/runner/work/larastan/larastan/vendor/laravel/framework/src/Illumina  
     te/Http/Response.php on line 48                                            
     Fatal error: Declaration of                                                
     Illuminate\Http\Response::setContent($content) must be compatible with     
     Symfony\Component\HttpFoundation\Response::setContent(?string $content):   
     static in                                                                  
     /home/runner/work/larastan/larastan/vendor/laravel/framework/src/Illumina  
     te/Http/Response.php on line 48                                            
                                                                                
     Child process error (exit code 255): PHP Fatal error:  Declaration of      
     Illuminate\Http\Request::duplicate(?array $query = null, ?array $request   
     = null, ?array $attributes = null, ?array $cookies = null, ?array $files   
     = null, ?array $server = null) must be compatible with                     
     Symfony\Component\HttpFoundation\Request::duplicate(?array $query = null,  
     ?array $request = null, ?array $attributes = null, ?array $cookies =       
     null, ?array $files = null, ?array $server = null): static in              
     /home/runner/work/larastan/larastan/vendor/laravel/framework/src/Illumina  
     te/Http/Request.php on line 445                                            
     Fatal error: Declaration of Illuminate\Http\Request::duplicate(?array      
     $query = null, ?array $request = null, ?array $attributes = null, ?array   
     $cookies = null, ?array $files = null, ?array $server = null) must be      
     compatible with                                                            
     Symfony\Component\HttpFoundation\Request::duplicate(?array $query = null,  
     ?array $request = null, ?array $attributes = null, ?array $cookies =       
     null, ?array $files = null, ?array $server = null): static in              
     /home/runner/work/larastan/larastan/vendor/laravel/framework/src/Illumina  
     te/Http/Request.php on line 445                                            
                                                                                
 -- ---------------------------------------------------------------------------
```

2021-08-14 17:25 UTC, szepeviktor commented
> Not sure that it is related to the PR 🤔

You are right. The last scheduled CI run was broken before this PR https://github.com/nunomaduro/larastan/actions

2021-08-14 17:33 UTC, szepeviktor approved these changes

2021-08-14 17:34 UTC, szepeviktor commented
Temporarily disabling tests on Laravel 9.
@LastDragon-ru We need 1 test that fails without this PR and single line of text in the changelog.

2021-08-14 18:09 UTC, szepeviktor commented on CHANGELOG.md
> +- Fixed "Dynamic call to static method `xxx()`." error for regular methods (!= macro) to work with [`phpstan-strict-rules`](https://github.com/phpstan/phpstan-strict-rules). ([#483](https://github.co
```suggestion
- Fixed Dynamic call to static method error for regular methods to work with [`phpstan-strict-rules`](https://github.com/phpstan/phpstan-strict-rules). ([#483](https://github.com/nunomaduro/larastan/issues/483), [#917](https://github.com/nunomaduro/larastan/pull/917))
```

2021-08-14 18:12 UTC, LastDragon-ru commented
> We need 1 test that fails without this PR and 

We have got a problem: it will fail only if https://github.com/phpstan/phpstan-strict-rules/ is installed, but it is not installed and I have no idea how to enable it for tests. (?)

Also, there is a similar problem with `Macroable`: larastan marks all methods `static` but they should be `static` and `non-static` at the same time (it is possible?), or we will have a lot of "Dynamic call to static method".


> single line of text in the changelog.

Fixed

2021-08-14 18:14 UTC, szepeviktor commented
All right.
Let's wait for @canvural

2021-09-12 21:37 UTC, canvural requested changes
Hi,

Thanks for the PR!

I think the change is small enough and looks correct. In this case we can get away with without a test. I just left 2 small comments, after those it should be ready to merge.

2021-09-12 21:37 UTC, canvural commented on .github/workflows/tests.yml
> +        laravel: ["^6.0", "^7.0", "^8.0"]
We allow Laravel 9 to fail. So I think this change is not needed.

2021-09-12 21:37 UTC, canvural commented on CHANGELOG.md
> +- Fixed Dynamic call to static method error for regular methods to work with [`phpstan-strict-rules`](https://github.com/phpstan/phpstan-strict-rules). ([#483](https://github.com/nunomaduro/larastan/
```suggestion
- Fixed `Dynamic call to static method` error for regular methods to work with [`phpstan-strict-rules`](https://github.com/phpstan/phpstan-strict-rules). ([#483](https://github.com/nunomaduro/larastan/issues/483), [#917](https://github.com/nunomaduro/larastan/pull/917))
```

2021-09-12 21:38 UTC, canvural commented
Ah, and there is a conflict to fix.

2021-09-16 16:34 UTC, LastDragon-ru commented
> Ah, and there is a conflict to fix.

@canvural fixed.

2021-09-22 09:29 UTC, merged

2021-09-22 09:30 UTC, canvural commented
Thank you!